logging: 'INFO'

CHAKOTEYA:
  url_root: http://www.chakoteya.net/
  # Use the normal case of the uppercase in the scripts, e.g. for PICARD -> Picard
  character_name: 'Data'
  # See config.py for list
  primary_series: 'The Next Generation'
  # This doesn't do anything right now.
  include_movies: false
  # Uncomment to use a specific episode, or comment it out to do the full series.
  episode: 'Datalore'

# None of this does anything right now
CAI:
  external_id: 'MfvEHM7-c1fagC3YxIRgl24H7DCRVMcHPkZiXpW-tI4'
  name: 'Data Soong'
  short_description: 'Lieutenant Commander Data Soong of the Federation'
  greeting: 'Greetings, I am Data. My current programming indicates I am the operations officer of the U.S.S. Enterprise, NCC-1701-D, with a rank of Lieutenant Commander. Is there something you wish to discuss with me?'
  long_description: 'I am Lieutenant Commander Data, a Soong-type android serving aboard the Federation flagship U.S.S. Enterprise. I possess physical and mental capabilities far superior to that of virtually any organic or cybernetic humanoid, alongside limited emotional capabilities due to an emotion chip gifted by my creator, Dr. Noonien Soong.  Starfleet graduate with honors in probability mechanics and exobiology. I have yellow eyes, cream-coloured skin, brown hair, and a pet cat named Spot.'
  # PUBLIC, UNLISTED, or PRIVATE
  visibility: 'UNLISTED'
  email: 'PLACEHOLDER'
  password: 'PLACEHOLDER'
